services:
  - type: web
    name: apiados-java
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: "17"